// Copyright 2021 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/*
Login to the platform.

To login to Mission Control, enter a valid mission control endpoint and give the server a name e.g. my-mission-control. Then follow the instructions to provide an API token.

To login to TKG Management cluster,  enter server endpoint which would be pinniped endpoint, and path to the cluster-info file. Providing these details is a temporary workaround till further details of cluster discovery process are figured out.

Sample cluster-info file:

	apiVersion: v1
	clusters:
	- cluster:
	  certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5ekNDQWJPZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01URXdOREl6TWprME9Wb1hEVE13TVRFd01qSXpNelEwT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1QrCnlXTW1kOENYRldSbU54RkdlbW9ZV201MSsySTZEZWdtT1d2WVllOFJSYjRqd0k1SzJQbDR6QjNXTkJLU2J3OGwKVzRKWFpaNWFBQ255Zk1hNjhtbk9nMGZvd01nZXptS2ZGdWpMc3ZNaS9rNEZkUGlHcDVSYWxHODZWZEZPUU1jaAo2Y3k5UTZuVmlWeVAzT05Sdnp3aWMvcGVqQ0hleGd3em5lNGZGbHAzdVdXOUJMam9pWjRGZjhmVUJZQTJERDUvCjVsbDl3Tmt2Z0hQNlc4OEZwZitzNmZRRWNEUWZwWHp0UTRDdWFJeFRyKzFETzVGV3l1aHd5b3o0aDlYc1NhTmMKT1dlSG1uN1JEVHFiUzlrMnFHNmkvVnR0Qys0Rzg0TDk5MkdrSkxLc0lZRFAwVDVKdzMwQ2JoQ1hPNEtsWTBOcQpGci9FVkZ6RU5nc3NiT2hUa0hzQ0F3RUFBYU1tTUNRd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR21ITzIxRVo1akJxQ3hvbDZlanNTTlYKeHFZMEdZc2Voc3ZtZWwwU2RoVEU4SGNMMk5nSWlzcnlmem91Q1QxT1c3ZzlpQ1dFQktvTzBmT2FMcU1tRHovOQpyTkZEWmk5Uk9CMVYvZmhaL05nUm1VV2tlakp2WEltREdqM1pHbDNOY3ZpQzBHV1U3aFc3NkoyU0s1OUYvZytPCmxTRDdZRExJSUJQWGNQeHgvUlp0MWwwMVV2Z1Uwb1dwYzFCNlNuSndCcXowMUViZFA3MEEvL3V2VGR4dWRhdUYKT0tVYkIxK0xTSGpVQTdtbWprTklKQ3VhZHVEZXpocjE4YjB2R3Nla0Y5dFo5OWtiM0QwUmM1SzQ1akh5QkgvOQpqTENJYldpRVg4SXV1U2o3NlA5OFBmcklEVDBMVkJOanAwY000eUFvMVpQYjR4Q3BsN2dsSzVTQUhzamRESm89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
	  server: https://tkg-test-mc-apiserver-1734810883.us-west-2.elb.amazonaws.com:6443
	  name: tkg-test-mc
*/
package main
