// Code generated by go-swagger; DO NOT EDIT.

package aws

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vmware-tanzu-private/core/pkg/v1/tkg/web/server/models"
)

// NewGenerateTKGConfigForAWSParams creates a new GenerateTKGConfigForAWSParams object
// with the default values initialized.
func NewGenerateTKGConfigForAWSParams() *GenerateTKGConfigForAWSParams {
	var ()
	return &GenerateTKGConfigForAWSParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateTKGConfigForAWSParamsWithTimeout creates a new GenerateTKGConfigForAWSParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGenerateTKGConfigForAWSParamsWithTimeout(timeout time.Duration) *GenerateTKGConfigForAWSParams {
	var ()
	return &GenerateTKGConfigForAWSParams{

		timeout: timeout,
	}
}

// NewGenerateTKGConfigForAWSParamsWithContext creates a new GenerateTKGConfigForAWSParams object
// with the default values initialized, and the ability to set a context for a request
func NewGenerateTKGConfigForAWSParamsWithContext(ctx context.Context) *GenerateTKGConfigForAWSParams {
	var ()
	return &GenerateTKGConfigForAWSParams{

		Context: ctx,
	}
}

// NewGenerateTKGConfigForAWSParamsWithHTTPClient creates a new GenerateTKGConfigForAWSParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGenerateTKGConfigForAWSParamsWithHTTPClient(client *http.Client) *GenerateTKGConfigForAWSParams {
	var ()
	return &GenerateTKGConfigForAWSParams{
		HTTPClient: client,
	}
}

/*GenerateTKGConfigForAWSParams contains all the parameters to send to the API endpoint
for the generate t k g config for a w s operation typically these are written to a http.Request
*/
type GenerateTKGConfigForAWSParams struct {

	/*Params
	  parameters to generate TKG configuration file for AWS

	*/
	Params *models.AWSRegionalClusterParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the generate t k g config for a w s params
func (o *GenerateTKGConfigForAWSParams) WithTimeout(timeout time.Duration) *GenerateTKGConfigForAWSParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate t k g config for a w s params
func (o *GenerateTKGConfigForAWSParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate t k g config for a w s params
func (o *GenerateTKGConfigForAWSParams) WithContext(ctx context.Context) *GenerateTKGConfigForAWSParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate t k g config for a w s params
func (o *GenerateTKGConfigForAWSParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate t k g config for a w s params
func (o *GenerateTKGConfigForAWSParams) WithHTTPClient(client *http.Client) *GenerateTKGConfigForAWSParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate t k g config for a w s params
func (o *GenerateTKGConfigForAWSParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParams adds the params to the generate t k g config for a w s params
func (o *GenerateTKGConfigForAWSParams) WithParams(params *models.AWSRegionalClusterParams) *GenerateTKGConfigForAWSParams {
	o.SetParams(params)
	return o
}

// SetParams adds the params to the generate t k g config for a w s params
func (o *GenerateTKGConfigForAWSParams) SetParams(params *models.AWSRegionalClusterParams) {
	o.Params = params
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateTKGConfigForAWSParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Params != nil {
		if err := r.SetBodyParam(o.Params); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
