// Code generated by go-swagger; DO NOT EDIT.

package aws

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vmware-tanzu/tanzu-framework/tkg/web/server/models"
)

// NewApplyTKGConfigForAWSParams creates a new ApplyTKGConfigForAWSParams object
// with the default values initialized.
func NewApplyTKGConfigForAWSParams() *ApplyTKGConfigForAWSParams {
	var ()
	return &ApplyTKGConfigForAWSParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewApplyTKGConfigForAWSParamsWithTimeout creates a new ApplyTKGConfigForAWSParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewApplyTKGConfigForAWSParamsWithTimeout(timeout time.Duration) *ApplyTKGConfigForAWSParams {
	var ()
	return &ApplyTKGConfigForAWSParams{

		timeout: timeout,
	}
}

// NewApplyTKGConfigForAWSParamsWithContext creates a new ApplyTKGConfigForAWSParams object
// with the default values initialized, and the ability to set a context for a request
func NewApplyTKGConfigForAWSParamsWithContext(ctx context.Context) *ApplyTKGConfigForAWSParams {
	var ()
	return &ApplyTKGConfigForAWSParams{

		Context: ctx,
	}
}

// NewApplyTKGConfigForAWSParamsWithHTTPClient creates a new ApplyTKGConfigForAWSParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewApplyTKGConfigForAWSParamsWithHTTPClient(client *http.Client) *ApplyTKGConfigForAWSParams {
	var ()
	return &ApplyTKGConfigForAWSParams{
		HTTPClient: client,
	}
}

/*
ApplyTKGConfigForAWSParams contains all the parameters to send to the API endpoint
for the apply t k g config for a w s operation typically these are written to a http.Request
*/
type ApplyTKGConfigForAWSParams struct {

	/*Params
	  parameters to apply changes to TKG configuration file for AWS

	*/
	Params *models.AWSRegionalClusterParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the apply t k g config for a w s params
func (o *ApplyTKGConfigForAWSParams) WithTimeout(timeout time.Duration) *ApplyTKGConfigForAWSParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apply t k g config for a w s params
func (o *ApplyTKGConfigForAWSParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apply t k g config for a w s params
func (o *ApplyTKGConfigForAWSParams) WithContext(ctx context.Context) *ApplyTKGConfigForAWSParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apply t k g config for a w s params
func (o *ApplyTKGConfigForAWSParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apply t k g config for a w s params
func (o *ApplyTKGConfigForAWSParams) WithHTTPClient(client *http.Client) *ApplyTKGConfigForAWSParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apply t k g config for a w s params
func (o *ApplyTKGConfigForAWSParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParams adds the params to the apply t k g config for a w s params
func (o *ApplyTKGConfigForAWSParams) WithParams(params *models.AWSRegionalClusterParams) *ApplyTKGConfigForAWSParams {
	o.SetParams(params)
	return o
}

// SetParams adds the params to the apply t k g config for a w s params
func (o *ApplyTKGConfigForAWSParams) SetParams(params *models.AWSRegionalClusterParams) {
	o.Params = params
}

// WriteToRequest writes these params to a swagger request
func (o *ApplyTKGConfigForAWSParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Params != nil {
		if err := r.SetBodyParam(o.Params); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
