//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2022 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Antrea) DeepCopyInto(out *Antrea) {
	*out = *in
	out.AntreaConfigDataValue = in.AntreaConfigDataValue
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Antrea.
func (in *Antrea) DeepCopy() *Antrea {
	if in == nil {
		return nil
	}
	out := new(Antrea)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaConfig) DeepCopyInto(out *AntreaConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaConfig.
func (in *AntreaConfig) DeepCopy() *AntreaConfig {
	if in == nil {
		return nil
	}
	out := new(AntreaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AntreaConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaConfigDataValue) DeepCopyInto(out *AntreaConfigDataValue) {
	*out = *in
	out.FeatureGates = in.FeatureGates
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaConfigDataValue.
func (in *AntreaConfigDataValue) DeepCopy() *AntreaConfigDataValue {
	if in == nil {
		return nil
	}
	out := new(AntreaConfigDataValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaConfigList) DeepCopyInto(out *AntreaConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AntreaConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaConfigList.
func (in *AntreaConfigList) DeepCopy() *AntreaConfigList {
	if in == nil {
		return nil
	}
	out := new(AntreaConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AntreaConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaConfigSpec) DeepCopyInto(out *AntreaConfigSpec) {
	*out = *in
	out.Antrea = in.Antrea
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaConfigSpec.
func (in *AntreaConfigSpec) DeepCopy() *AntreaConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AntreaConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaConfigStatus) DeepCopyInto(out *AntreaConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaConfigStatus.
func (in *AntreaConfigStatus) DeepCopy() *AntreaConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AntreaConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntreaFeatureGates) DeepCopyInto(out *AntreaFeatureGates) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntreaFeatureGates.
func (in *AntreaFeatureGates) DeepCopy() *AntreaFeatureGates {
	if in == nil {
		return nil
	}
	out := new(AntreaFeatureGates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Calico) DeepCopyInto(out *Calico) {
	*out = *in
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Calico.
func (in *Calico) DeepCopy() *Calico {
	if in == nil {
		return nil
	}
	out := new(Calico)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalicoConfig) DeepCopyInto(out *CalicoConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalicoConfig.
func (in *CalicoConfig) DeepCopy() *CalicoConfig {
	if in == nil {
		return nil
	}
	out := new(CalicoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CalicoConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalicoConfigDataValue) DeepCopyInto(out *CalicoConfigDataValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalicoConfigDataValue.
func (in *CalicoConfigDataValue) DeepCopy() *CalicoConfigDataValue {
	if in == nil {
		return nil
	}
	out := new(CalicoConfigDataValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalicoConfigList) DeepCopyInto(out *CalicoConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CalicoConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalicoConfigList.
func (in *CalicoConfigList) DeepCopy() *CalicoConfigList {
	if in == nil {
		return nil
	}
	out := new(CalicoConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CalicoConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalicoConfigSpec) DeepCopyInto(out *CalicoConfigSpec) {
	*out = *in
	out.Calico = in.Calico
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalicoConfigSpec.
func (in *CalicoConfigSpec) DeepCopy() *CalicoConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CalicoConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalicoConfigStatus) DeepCopyInto(out *CalicoConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalicoConfigStatus.
func (in *CalicoConfigStatus) DeepCopy() *CalicoConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CalicoConfigStatus)
	in.DeepCopyInto(out)
	return out
}
