// Code generated by go-swagger; DO NOT EDIT.

package ldap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVerifyLdapCloseConnectionParams creates a new VerifyLdapCloseConnectionParams object
// with the default values initialized.
func NewVerifyLdapCloseConnectionParams() *VerifyLdapCloseConnectionParams {

	return &VerifyLdapCloseConnectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVerifyLdapCloseConnectionParamsWithTimeout creates a new VerifyLdapCloseConnectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVerifyLdapCloseConnectionParamsWithTimeout(timeout time.Duration) *VerifyLdapCloseConnectionParams {

	return &VerifyLdapCloseConnectionParams{

		timeout: timeout,
	}
}

// NewVerifyLdapCloseConnectionParamsWithContext creates a new VerifyLdapCloseConnectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewVerifyLdapCloseConnectionParamsWithContext(ctx context.Context) *VerifyLdapCloseConnectionParams {

	return &VerifyLdapCloseConnectionParams{

		Context: ctx,
	}
}

// NewVerifyLdapCloseConnectionParamsWithHTTPClient creates a new VerifyLdapCloseConnectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVerifyLdapCloseConnectionParamsWithHTTPClient(client *http.Client) *VerifyLdapCloseConnectionParams {

	return &VerifyLdapCloseConnectionParams{
		HTTPClient: client,
	}
}

/*
VerifyLdapCloseConnectionParams contains all the parameters to send to the API endpoint
for the verify ldap close connection operation typically these are written to a http.Request
*/
type VerifyLdapCloseConnectionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the verify ldap close connection params
func (o *VerifyLdapCloseConnectionParams) WithTimeout(timeout time.Duration) *VerifyLdapCloseConnectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the verify ldap close connection params
func (o *VerifyLdapCloseConnectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the verify ldap close connection params
func (o *VerifyLdapCloseConnectionParams) WithContext(ctx context.Context) *VerifyLdapCloseConnectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the verify ldap close connection params
func (o *VerifyLdapCloseConnectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the verify ldap close connection params
func (o *VerifyLdapCloseConnectionParams) WithHTTPClient(client *http.Client) *VerifyLdapCloseConnectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the verify ldap close connection params
func (o *VerifyLdapCloseConnectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *VerifyLdapCloseConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
