// Code generated by go-swagger; DO NOT EDIT.

package ldap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVerifyLdapBindParams creates a new VerifyLdapBindParams object
// with the default values initialized.
func NewVerifyLdapBindParams() *VerifyLdapBindParams {

	return &VerifyLdapBindParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVerifyLdapBindParamsWithTimeout creates a new VerifyLdapBindParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVerifyLdapBindParamsWithTimeout(timeout time.Duration) *VerifyLdapBindParams {

	return &VerifyLdapBindParams{

		timeout: timeout,
	}
}

// NewVerifyLdapBindParamsWithContext creates a new VerifyLdapBindParams object
// with the default values initialized, and the ability to set a context for a request
func NewVerifyLdapBindParamsWithContext(ctx context.Context) *VerifyLdapBindParams {

	return &VerifyLdapBindParams{

		Context: ctx,
	}
}

// NewVerifyLdapBindParamsWithHTTPClient creates a new VerifyLdapBindParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVerifyLdapBindParamsWithHTTPClient(client *http.Client) *VerifyLdapBindParams {

	return &VerifyLdapBindParams{
		HTTPClient: client,
	}
}

/*
VerifyLdapBindParams contains all the parameters to send to the API endpoint
for the verify ldap bind operation typically these are written to a http.Request
*/
type VerifyLdapBindParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the verify ldap bind params
func (o *VerifyLdapBindParams) WithTimeout(timeout time.Duration) *VerifyLdapBindParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the verify ldap bind params
func (o *VerifyLdapBindParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the verify ldap bind params
func (o *VerifyLdapBindParams) WithContext(ctx context.Context) *VerifyLdapBindParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the verify ldap bind params
func (o *VerifyLdapBindParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the verify ldap bind params
func (o *VerifyLdapBindParams) WithHTTPClient(client *http.Client) *VerifyLdapBindParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the verify ldap bind params
func (o *VerifyLdapBindParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *VerifyLdapBindParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
