// Copyright 2021 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/avi (interfaces: MiniNetworkClient)

// Package avi is a generated GoMock package.
package avi

import (
	reflect "reflect"

	models "github.com/avinetworks/sdk/go/models"
	session "github.com/avinetworks/sdk/go/session"
	gomock "github.com/golang/mock/gomock"
)

// MockMiniNetworkClient is a mock of MiniNetworkClient interface
type MockMiniNetworkClient struct {
	ctrl     *gomock.Controller
	recorder *MockMiniNetworkClientMockRecorder
}

// MockMiniNetworkClientMockRecorder is the mock recorder for MockMiniNetworkClient
type MockMiniNetworkClientMockRecorder struct {
	mock *MockMiniNetworkClient
}

// NewMockMiniNetworkClient creates a new mock instance
func NewMockMiniNetworkClient(ctrl *gomock.Controller) *MockMiniNetworkClient {
	mock := &MockMiniNetworkClient{ctrl: ctrl}
	mock.recorder = &MockMiniNetworkClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMiniNetworkClient) EXPECT() *MockMiniNetworkClientMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockMiniNetworkClient) GetAll(arg0 ...session.ApiOptionsParams) ([]*models.Network, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].([]*models.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockMiniNetworkClientMockRecorder) GetAll(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMiniNetworkClient)(nil).GetAll), arg0...)
}
