// Copyright 2021 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/avi (interfaces: MiniCloudClient)

// Package avi is a generated GoMock package.
package avi

import (
	reflect "reflect"

	models "github.com/avinetworks/sdk/go/models"
	session "github.com/avinetworks/sdk/go/session"
	gomock "github.com/golang/mock/gomock"
)

// MockMiniCloudClient is a mock of MiniCloudClient interface
type MockMiniCloudClient struct {
	ctrl     *gomock.Controller
	recorder *MockMiniCloudClientMockRecorder
}

// MockMiniCloudClientMockRecorder is the mock recorder for MockMiniCloudClient
type MockMiniCloudClientMockRecorder struct {
	mock *MockMiniCloudClient
}

// NewMockMiniCloudClient creates a new mock instance
func NewMockMiniCloudClient(ctrl *gomock.Controller) *MockMiniCloudClient {
	mock := &MockMiniCloudClient{ctrl: ctrl}
	mock.recorder = &MockMiniCloudClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMiniCloudClient) EXPECT() *MockMiniCloudClientMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockMiniCloudClient) GetAll(arg0 ...session.ApiOptionsParams) ([]*models.Cloud, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAll", varargs...)
	ret0, _ := ret[0].([]*models.Cloud)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockMiniCloudClientMockRecorder) GetAll(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMiniCloudClient)(nil).GetAll), arg0...)
}
