// Code generated by go-swagger; DO NOT EDIT.

package azure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vmware-tanzu/tanzu-framework/tkg/web/server/models"
)

// NewApplyTKGConfigForAzureParams creates a new ApplyTKGConfigForAzureParams object
// with the default values initialized.
func NewApplyTKGConfigForAzureParams() *ApplyTKGConfigForAzureParams {
	var ()
	return &ApplyTKGConfigForAzureParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewApplyTKGConfigForAzureParamsWithTimeout creates a new ApplyTKGConfigForAzureParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewApplyTKGConfigForAzureParamsWithTimeout(timeout time.Duration) *ApplyTKGConfigForAzureParams {
	var ()
	return &ApplyTKGConfigForAzureParams{

		timeout: timeout,
	}
}

// NewApplyTKGConfigForAzureParamsWithContext creates a new ApplyTKGConfigForAzureParams object
// with the default values initialized, and the ability to set a context for a request
func NewApplyTKGConfigForAzureParamsWithContext(ctx context.Context) *ApplyTKGConfigForAzureParams {
	var ()
	return &ApplyTKGConfigForAzureParams{

		Context: ctx,
	}
}

// NewApplyTKGConfigForAzureParamsWithHTTPClient creates a new ApplyTKGConfigForAzureParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewApplyTKGConfigForAzureParamsWithHTTPClient(client *http.Client) *ApplyTKGConfigForAzureParams {
	var ()
	return &ApplyTKGConfigForAzureParams{
		HTTPClient: client,
	}
}

/*
ApplyTKGConfigForAzureParams contains all the parameters to send to the API endpoint
for the apply t k g config for azure operation typically these are written to a http.Request
*/
type ApplyTKGConfigForAzureParams struct {

	/*Params
	  parameters to apply changes to TKG configuration file for Azure

	*/
	Params *models.AzureRegionalClusterParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the apply t k g config for azure params
func (o *ApplyTKGConfigForAzureParams) WithTimeout(timeout time.Duration) *ApplyTKGConfigForAzureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apply t k g config for azure params
func (o *ApplyTKGConfigForAzureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apply t k g config for azure params
func (o *ApplyTKGConfigForAzureParams) WithContext(ctx context.Context) *ApplyTKGConfigForAzureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apply t k g config for azure params
func (o *ApplyTKGConfigForAzureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apply t k g config for azure params
func (o *ApplyTKGConfigForAzureParams) WithHTTPClient(client *http.Client) *ApplyTKGConfigForAzureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apply t k g config for azure params
func (o *ApplyTKGConfigForAzureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParams adds the params to the apply t k g config for azure params
func (o *ApplyTKGConfigForAzureParams) WithParams(params *models.AzureRegionalClusterParams) *ApplyTKGConfigForAzureParams {
	o.SetParams(params)
	return o
}

// SetParams adds the params to the apply t k g config for azure params
func (o *ApplyTKGConfigForAzureParams) SetParams(params *models.AzureRegionalClusterParams) {
	o.Params = params
}

// WriteToRequest writes these params to a swagger request
func (o *ApplyTKGConfigForAzureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Params != nil {
		if err := r.SetBodyParam(o.Params); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
