// Code generated by go-swagger; DO NOT EDIT.

package azure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAzureRegionsParams creates a new GetAzureRegionsParams object
// with the default values initialized.
func NewGetAzureRegionsParams() *GetAzureRegionsParams {

	return &GetAzureRegionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAzureRegionsParamsWithTimeout creates a new GetAzureRegionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAzureRegionsParamsWithTimeout(timeout time.Duration) *GetAzureRegionsParams {

	return &GetAzureRegionsParams{

		timeout: timeout,
	}
}

// NewGetAzureRegionsParamsWithContext creates a new GetAzureRegionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAzureRegionsParamsWithContext(ctx context.Context) *GetAzureRegionsParams {

	return &GetAzureRegionsParams{

		Context: ctx,
	}
}

// NewGetAzureRegionsParamsWithHTTPClient creates a new GetAzureRegionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAzureRegionsParamsWithHTTPClient(client *http.Client) *GetAzureRegionsParams {

	return &GetAzureRegionsParams{
		HTTPClient: client,
	}
}

/*
GetAzureRegionsParams contains all the parameters to send to the API endpoint
for the get azure regions operation typically these are written to a http.Request
*/
type GetAzureRegionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get azure regions params
func (o *GetAzureRegionsParams) WithTimeout(timeout time.Duration) *GetAzureRegionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get azure regions params
func (o *GetAzureRegionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get azure regions params
func (o *GetAzureRegionsParams) WithContext(ctx context.Context) *GetAzureRegionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get azure regions params
func (o *GetAzureRegionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get azure regions params
func (o *GetAzureRegionsParams) WithHTTPClient(client *http.Client) *GetAzureRegionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get azure regions params
func (o *GetAzureRegionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAzureRegionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
