// Code generated by go-swagger; DO NOT EDIT.

package azure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAzureResourceGroupsParams creates a new GetAzureResourceGroupsParams object
// with the default values initialized.
func NewGetAzureResourceGroupsParams() *GetAzureResourceGroupsParams {
	var ()
	return &GetAzureResourceGroupsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAzureResourceGroupsParamsWithTimeout creates a new GetAzureResourceGroupsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAzureResourceGroupsParamsWithTimeout(timeout time.Duration) *GetAzureResourceGroupsParams {
	var ()
	return &GetAzureResourceGroupsParams{

		timeout: timeout,
	}
}

// NewGetAzureResourceGroupsParamsWithContext creates a new GetAzureResourceGroupsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAzureResourceGroupsParamsWithContext(ctx context.Context) *GetAzureResourceGroupsParams {
	var ()
	return &GetAzureResourceGroupsParams{

		Context: ctx,
	}
}

// NewGetAzureResourceGroupsParamsWithHTTPClient creates a new GetAzureResourceGroupsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAzureResourceGroupsParamsWithHTTPClient(client *http.Client) *GetAzureResourceGroupsParams {
	var ()
	return &GetAzureResourceGroupsParams{
		HTTPClient: client,
	}
}

/*
GetAzureResourceGroupsParams contains all the parameters to send to the API endpoint
for the get azure resource groups operation typically these are written to a http.Request
*/
type GetAzureResourceGroupsParams struct {

	/*Location
	  Azure region

	*/
	Location string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get azure resource groups params
func (o *GetAzureResourceGroupsParams) WithTimeout(timeout time.Duration) *GetAzureResourceGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get azure resource groups params
func (o *GetAzureResourceGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get azure resource groups params
func (o *GetAzureResourceGroupsParams) WithContext(ctx context.Context) *GetAzureResourceGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get azure resource groups params
func (o *GetAzureResourceGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get azure resource groups params
func (o *GetAzureResourceGroupsParams) WithHTTPClient(client *http.Client) *GetAzureResourceGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get azure resource groups params
func (o *GetAzureResourceGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLocation adds the location to the get azure resource groups params
func (o *GetAzureResourceGroupsParams) WithLocation(location string) *GetAzureResourceGroupsParams {
	o.SetLocation(location)
	return o
}

// SetLocation adds the location to the get azure resource groups params
func (o *GetAzureResourceGroupsParams) SetLocation(location string) {
	o.Location = location
}

// WriteToRequest writes these params to a swagger request
func (o *GetAzureResourceGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param location
	qrLocation := o.Location
	qLocation := qrLocation
	if qLocation != "" {
		if err := r.SetQueryParam("location", qLocation); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
