// Code generated by go-swagger; DO NOT EDIT.

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vmware-tanzu/tanzu-framework/tkg/web/server/models"
)

// GetProviderReader is a Reader for the GetProvider structure.
type GetProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProviderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProviderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProviderInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProviderOK creates a GetProviderOK with default headers values
func NewGetProviderOK() *GetProviderOK {
	return &GetProviderOK{}
}

/*
GetProviderOK handles this case with default header values.

Successful operation
*/
type GetProviderOK struct {
	Payload *models.ProviderInfo
}

func (o *GetProviderOK) Error() string {
	return fmt.Sprintf("[GET /api/providers][%d] getProviderOK  %+v", 200, o.Payload)
}

func (o *GetProviderOK) GetPayload() *models.ProviderInfo {
	return o.Payload
}

func (o *GetProviderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProviderInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProviderBadRequest creates a GetProviderBadRequest with default headers values
func NewGetProviderBadRequest() *GetProviderBadRequest {
	return &GetProviderBadRequest{}
}

/*
GetProviderBadRequest handles this case with default header values.

Bad request
*/
type GetProviderBadRequest struct {
	Payload *models.Error
}

func (o *GetProviderBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/providers][%d] getProviderBadRequest  %+v", 400, o.Payload)
}

func (o *GetProviderBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetProviderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProviderInternalServerError creates a GetProviderInternalServerError with default headers values
func NewGetProviderInternalServerError() *GetProviderInternalServerError {
	return &GetProviderInternalServerError{}
}

/*
GetProviderInternalServerError handles this case with default header values.

Internal server error
*/
type GetProviderInternalServerError struct {
	Payload *models.Error
}

func (o *GetProviderInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/providers][%d] getProviderInternalServerError  %+v", 500, o.Payload)
}

func (o *GetProviderInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetProviderInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
