// Code generated by go-swagger; DO NOT EDIT.

package vsphere

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vmware-tanzu/tanzu-framework/tkg/web/server/models"
)

// NewImportTKGConfigForVsphereParams creates a new ImportTKGConfigForVsphereParams object
// with the default values initialized.
func NewImportTKGConfigForVsphereParams() *ImportTKGConfigForVsphereParams {
	var ()
	return &ImportTKGConfigForVsphereParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewImportTKGConfigForVsphereParamsWithTimeout creates a new ImportTKGConfigForVsphereParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewImportTKGConfigForVsphereParamsWithTimeout(timeout time.Duration) *ImportTKGConfigForVsphereParams {
	var ()
	return &ImportTKGConfigForVsphereParams{

		timeout: timeout,
	}
}

// NewImportTKGConfigForVsphereParamsWithContext creates a new ImportTKGConfigForVsphereParams object
// with the default values initialized, and the ability to set a context for a request
func NewImportTKGConfigForVsphereParamsWithContext(ctx context.Context) *ImportTKGConfigForVsphereParams {
	var ()
	return &ImportTKGConfigForVsphereParams{

		Context: ctx,
	}
}

// NewImportTKGConfigForVsphereParamsWithHTTPClient creates a new ImportTKGConfigForVsphereParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewImportTKGConfigForVsphereParamsWithHTTPClient(client *http.Client) *ImportTKGConfigForVsphereParams {
	var ()
	return &ImportTKGConfigForVsphereParams{
		HTTPClient: client,
	}
}

/*
ImportTKGConfigForVsphereParams contains all the parameters to send to the API endpoint
for the import t k g config for vsphere operation typically these are written to a http.Request
*/
type ImportTKGConfigForVsphereParams struct {

	/*Params
	  config file from which to generate tkg configuration for vsphere

	*/
	Params *models.ConfigFile

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the import t k g config for vsphere params
func (o *ImportTKGConfigForVsphereParams) WithTimeout(timeout time.Duration) *ImportTKGConfigForVsphereParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the import t k g config for vsphere params
func (o *ImportTKGConfigForVsphereParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the import t k g config for vsphere params
func (o *ImportTKGConfigForVsphereParams) WithContext(ctx context.Context) *ImportTKGConfigForVsphereParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the import t k g config for vsphere params
func (o *ImportTKGConfigForVsphereParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the import t k g config for vsphere params
func (o *ImportTKGConfigForVsphereParams) WithHTTPClient(client *http.Client) *ImportTKGConfigForVsphereParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the import t k g config for vsphere params
func (o *ImportTKGConfigForVsphereParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParams adds the params to the import t k g config for vsphere params
func (o *ImportTKGConfigForVsphereParams) WithParams(params *models.ConfigFile) *ImportTKGConfigForVsphereParams {
	o.SetParams(params)
	return o
}

// SetParams adds the params to the import t k g config for vsphere params
func (o *ImportTKGConfigForVsphereParams) SetParams(params *models.ConfigFile) {
	o.Params = params
}

// WriteToRequest writes these params to a swagger request
func (o *ImportTKGConfigForVsphereParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Params != nil {
		if err := r.SetBodyParam(o.Params); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
