// Code generated by go-swagger; DO NOT EDIT.

package azure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GenerateTKGConfigForAzureHandlerFunc turns a function with the right signature into a generate t k g config for azure handler
type GenerateTKGConfigForAzureHandlerFunc func(GenerateTKGConfigForAzureParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GenerateTKGConfigForAzureHandlerFunc) Handle(params GenerateTKGConfigForAzureParams) middleware.Responder {
	return fn(params)
}

// GenerateTKGConfigForAzureHandler interface for that can handle valid generate t k g config for azure params
type GenerateTKGConfigForAzureHandler interface {
	Handle(GenerateTKGConfigForAzureParams) middleware.Responder
}

// NewGenerateTKGConfigForAzure creates a new http.Handler for the generate t k g config for azure operation
func NewGenerateTKGConfigForAzure(ctx *middleware.Context, handler GenerateTKGConfigForAzureHandler) *GenerateTKGConfigForAzure {
	return &GenerateTKGConfigForAzure{Context: ctx, Handler: handler}
}

/*GenerateTKGConfigForAzure swagger:route POST /api/providers/azure/generate azure generateTKGConfigForAzure

Generate TKG configuration file for Azure"

*/
type GenerateTKGConfigForAzure struct {
	Context *middleware.Context
	Handler GenerateTKGConfigForAzureHandler
}

func (o *GenerateTKGConfigForAzure) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGenerateTKGConfigForAzureParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
