// Code generated by go-swagger; DO NOT EDIT.

package azure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vmware-tanzu-private/core/pkg/v1/tkg/web/server/models"
)

// NewGenerateTKGConfigForAzureParams creates a new GenerateTKGConfigForAzureParams object
// with the default values initialized.
func NewGenerateTKGConfigForAzureParams() *GenerateTKGConfigForAzureParams {
	var ()
	return &GenerateTKGConfigForAzureParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateTKGConfigForAzureParamsWithTimeout creates a new GenerateTKGConfigForAzureParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGenerateTKGConfigForAzureParamsWithTimeout(timeout time.Duration) *GenerateTKGConfigForAzureParams {
	var ()
	return &GenerateTKGConfigForAzureParams{

		timeout: timeout,
	}
}

// NewGenerateTKGConfigForAzureParamsWithContext creates a new GenerateTKGConfigForAzureParams object
// with the default values initialized, and the ability to set a context for a request
func NewGenerateTKGConfigForAzureParamsWithContext(ctx context.Context) *GenerateTKGConfigForAzureParams {
	var ()
	return &GenerateTKGConfigForAzureParams{

		Context: ctx,
	}
}

// NewGenerateTKGConfigForAzureParamsWithHTTPClient creates a new GenerateTKGConfigForAzureParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGenerateTKGConfigForAzureParamsWithHTTPClient(client *http.Client) *GenerateTKGConfigForAzureParams {
	var ()
	return &GenerateTKGConfigForAzureParams{
		HTTPClient: client,
	}
}

/*GenerateTKGConfigForAzureParams contains all the parameters to send to the API endpoint
for the generate t k g config for azure operation typically these are written to a http.Request
*/
type GenerateTKGConfigForAzureParams struct {

	/*Params
	  parameters to generate TKG configuration file for Azure

	*/
	Params *models.AzureRegionalClusterParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the generate t k g config for azure params
func (o *GenerateTKGConfigForAzureParams) WithTimeout(timeout time.Duration) *GenerateTKGConfigForAzureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate t k g config for azure params
func (o *GenerateTKGConfigForAzureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate t k g config for azure params
func (o *GenerateTKGConfigForAzureParams) WithContext(ctx context.Context) *GenerateTKGConfigForAzureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate t k g config for azure params
func (o *GenerateTKGConfigForAzureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate t k g config for azure params
func (o *GenerateTKGConfigForAzureParams) WithHTTPClient(client *http.Client) *GenerateTKGConfigForAzureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate t k g config for azure params
func (o *GenerateTKGConfigForAzureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParams adds the params to the generate t k g config for azure params
func (o *GenerateTKGConfigForAzureParams) WithParams(params *models.AzureRegionalClusterParams) *GenerateTKGConfigForAzureParams {
	o.SetParams(params)
	return o
}

// SetParams adds the params to the generate t k g config for azure params
func (o *GenerateTKGConfigForAzureParams) SetParams(params *models.AzureRegionalClusterParams) {
	o.Params = params
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateTKGConfigForAzureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Params != nil {
		if err := r.SetBodyParam(o.Params); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
